export enum ApiErrorType {
  CONVERSATION_OBJECTIVE_NAME_ALREADY_EXISTS = 'CONVERSATION_OBJECTIVE_NAME_ALREADY_EXISTS',
  CONVERSATION_OUTCOME_NAME_ALREADY_EXISTS = 'CONVERSATION_OUTCOME_NAME_ALREADY_EXISTS',
  CONVERSATION_OBJECTIVE_AND_OUTCOME_NEEDED = 'CONVERSATION_OBJECTIVE_AND_OUTCOME_NEEDED',
}
